const resources = [
  {
    name: 'users',
    tableName: 'users',
    primaryKey: 'id',
    requiredFields: ['email', 'password', 'username'],
    writableFields: [
      'email',
      'password',
      'username',
      'bio',
      'profileImage',
      'displayNameColor',
      'profileFrameStyle',
      'theme',
      'displayMode',
      'language',
      'notifications',
      'isPremium',
      'premiumExpiresAt',
      'billingMethod',
      'twoFAEnabled',
      'twoFAMethod',
      'twoFASecret',
      'whoCanInvite',
      'acceptStrangerMessages',
      'friendsList',
      'blockedUsers',
      'communities',
      'colorblindMode',
      'highContrast',
      'textSize',
      'audioInputDevice',
      'audioOutputDevice',
      'volume',
      'lastUsernameChange',
    ],
    jsonFields: ['notifications', 'friendsList', 'blockedUsers', 'communities'],
    booleanFields: ['isPremium', 'twoFAEnabled', 'acceptStrangerMessages', 'highContrast'],
    sensitiveFields: ['password', 'twoFASecret'],
    description: 'Gestione utenti, profilo, impostazioni e relazioni.',
  },
  {
    name: 'animes',
    tableName: 'animes',
    primaryKey: 'id',
    requiredFields: ['title', 'platforms', 'hashtags'],
    writableFields: [
      'title',
      'description',
      'coverImage',
      'rating',
      'category',
      'status',
      'jikanId',
      'anilistId',
      'kitsuId',
      'platforms',
      'hashtags',
      'followedByCount',
    ],
    jsonFields: ['platforms', 'hashtags'],
    booleanFields: [],
    sensitiveFields: [],
    description: 'Catalogo anime e metadati collegati.',
  },
  {
    name: 'roles',
    tableName: 'roles',
    primaryKey: 'id',
    requiredFields: ['name', 'permissions', 'members'],
    writableFields: ['name', 'permissions', 'color', 'members'],
    jsonFields: ['permissions', 'members'],
    booleanFields: [],
    sensitiveFields: [],
    description: 'Ruoli di community con permessi e membri.',
  },
  {
    name: 'channels',
    tableName: 'channels',
    primaryKey: 'id',
    requiredFields: ['name', 'type', 'hashtags', 'permissions', 'messages', 'members'],
    writableFields: ['name', 'type', 'hashtags', 'maxMembers', 'permissions', 'messages', 'members'],
    jsonFields: ['hashtags', 'permissions', 'messages', 'members'],
    booleanFields: [],
    sensitiveFields: [],
    description: 'Canali testuali o vocali della piattaforma.',
  },
  {
    name: 'channel-groups',
    tableName: 'channel_groups',
    primaryKey: 'id',
    requiredFields: ['name', 'channels'],
    writableFields: ['name', 'channels'],
    jsonFields: ['channels'],
    booleanFields: [],
    sensitiveFields: [],
    description: 'Gruppi organizzativi di canali.',
  },
  {
    name: 'communities',
    tableName: 'communities',
    primaryKey: 'id',
    requiredFields: ['name', 'adminId', 'roles', 'categories', 'channelGroups', 'members', 'pinnedMessages'],
    writableFields: ['name', 'description', 'adminId', 'roles', 'categories', 'channelGroups', 'members', 'pinnedMessages'],
    jsonFields: ['roles', 'categories', 'channelGroups', 'members', 'pinnedMessages'],
    booleanFields: [],
    sensitiveFields: [],
    description: 'Community con struttura, membri e contenuti.',
  },
  {
    name: 'direct-messages',
    tableName: 'direct_messages',
    primaryKey: 'id',
    requiredFields: ['participants', 'messages'],
    writableFields: ['participants', 'messages'],
    jsonFields: ['participants', 'messages'],
    booleanFields: [],
    sensitiveFields: [],
    description: 'Sessioni di chat privata tra utenti.',
  },
  {
    name: 'messages',
    tableName: 'messages',
    primaryKey: 'id',
    requiredFields: ['content', 'authorId', 'reactions', 'mentions'],
    writableFields: ['content', 'authorId', 'channelId', 'dmSessionId', 'timestamp', 'isPinned', 'reactions', 'mentions'],
    jsonFields: ['reactions', 'mentions'],
    booleanFields: ['isPinned'],
    sensitiveFields: [],
    description: 'Messaggi associati a canali o chat dirette.',
  },
  {
    name: 'friendships',
    tableName: 'friendships',
    primaryKey: 'id',
    requiredFields: ['requester', 'recipient', 'status'],
    writableFields: ['requester', 'recipient', 'status'],
    jsonFields: [],
    booleanFields: [],
    sensitiveFields: [],
    description: 'Richieste e relazioni di amicizia tra utenti.',
  },
];

const resourceMap = Object.fromEntries(resources.map((resource) => [resource.name, resource]));

module.exports = {
  resources,
  resourceMap,
};
