const schemaStatements = [
  `CREATE TABLE IF NOT EXISTS users (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    username VARCHAR(20) NOT NULL,
    bio TEXT NULL,
    profileImage VARCHAR(255) NOT NULL DEFAULT '',
    displayNameColor VARCHAR(20) NOT NULL DEFAULT '#000000',
    profileFrameStyle VARCHAR(50) NOT NULL DEFAULT 'default',
    theme ENUM('light', 'dark', 'auto') NOT NULL DEFAULT 'auto',
    displayMode ENUM('light', 'dark') NOT NULL DEFAULT 'light',
    language VARCHAR(10) NOT NULL DEFAULT 'it',
    notifications JSON NOT NULL,
    isPremium TINYINT(1) NOT NULL DEFAULT 0,
    premiumExpiresAt DATETIME NULL,
    billingMethod ENUM('credit_card', 'debit_card', 'prepaid') NULL,
    twoFAEnabled TINYINT(1) NOT NULL DEFAULT 0,
    twoFAMethod ENUM('phone', 'email', 'app') NULL,
    twoFASecret VARCHAR(255) NULL,
    publicKey TEXT NULL,
    whoCanInvite ENUM('all', 'friends', 'none') NOT NULL DEFAULT 'all',
    acceptStrangerMessages TINYINT(1) NOT NULL DEFAULT 0,
    friendsList JSON NOT NULL,
    blockedUsers JSON NOT NULL,
    communities JSON NOT NULL,
    colorblindMode ENUM('normal', 'protanopia', 'deuteranopia', 'tritanopia') NOT NULL DEFAULT 'normal',
    highContrast TINYINT(1) NOT NULL DEFAULT 0,
    textSize DECIMAL(4,2) NOT NULL DEFAULT 0.75,
    audioInputDevice VARCHAR(100) NOT NULL DEFAULT 'default',
    audioOutputDevice VARCHAR(100) NOT NULL DEFAULT 'default',
    volume INT NOT NULL DEFAULT 80,
    lastUsernameChange DATETIME NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deletedAt DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_users_email (email),
    UNIQUE KEY uq_users_username (username)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
  `CREATE TABLE IF NOT EXISTS animes (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    description TEXT NULL,
    coverImage VARCHAR(255) NOT NULL DEFAULT '',
    rating DECIMAL(3,1) NOT NULL DEFAULT 0.0,
    category VARCHAR(255) NOT NULL DEFAULT '',
    status ENUM('ongoing', 'completed', 'upcoming') NOT NULL DEFAULT 'ongoing',
    jikanId INT NULL,
    anilistId INT NULL,
    kitsuId INT NULL,
    platforms JSON NOT NULL,
    hashtags JSON NOT NULL,
    followedByCount INT NOT NULL DEFAULT 0,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deletedAt DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_animes_title (title)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
  `CREATE TABLE IF NOT EXISTS roles (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    permissions JSON NOT NULL,
    color VARCHAR(20) NOT NULL DEFAULT '#000000',
    members JSON NOT NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deletedAt DATETIME NULL,
    PRIMARY KEY (id)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
  `CREATE TABLE IF NOT EXISTS channels (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    type ENUM('text', 'voice') NOT NULL,
    hashtags JSON NOT NULL,
    maxMembers INT NOT NULL DEFAULT 10,
    permissions JSON NOT NULL,
    messages JSON NOT NULL,
    members JSON NOT NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deletedAt DATETIME NULL,
    PRIMARY KEY (id)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
  `CREATE TABLE IF NOT EXISTS channel_groups (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    channels JSON NOT NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deletedAt DATETIME NULL,
    PRIMARY KEY (id)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
  `CREATE TABLE IF NOT EXISTS communities (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(150) NOT NULL,
    description TEXT NULL,
    adminId INT UNSIGNED NOT NULL,
    roles JSON NOT NULL,
    categories JSON NOT NULL,
    channelGroups JSON NOT NULL,
    members JSON NOT NULL,
    pinnedMessages JSON NOT NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deletedAt DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_communities_admin_name (adminId, name),
    CONSTRAINT fk_communities_admin FOREIGN KEY (adminId) REFERENCES users (id)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
  `CREATE TABLE IF NOT EXISTS direct_messages (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    participants JSON NOT NULL,
    messages JSON NOT NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deletedAt DATETIME NULL,
    PRIMARY KEY (id)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
  `CREATE TABLE IF NOT EXISTS messages (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    content TEXT NOT NULL,
    authorId INT UNSIGNED NOT NULL,
    channelId INT UNSIGNED NULL,
    dmSessionId INT UNSIGNED NULL,
    timestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    isPinned TINYINT(1) NOT NULL DEFAULT 0,
    reactions JSON NOT NULL,
    mentions JSON NOT NULL,
    deletedAt DATETIME NULL,
    PRIMARY KEY (id),
    KEY idx_messages_channel_timestamp (channelId, timestamp),
    KEY idx_messages_dm_timestamp (dmSessionId, timestamp),
    CONSTRAINT fk_messages_author FOREIGN KEY (authorId) REFERENCES users (id),
    CONSTRAINT fk_messages_channel FOREIGN KEY (channelId) REFERENCES channels (id),
    CONSTRAINT fk_messages_dm FOREIGN KEY (dmSessionId) REFERENCES direct_messages (id)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
  `CREATE TABLE IF NOT EXISTS friendships (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    requester INT UNSIGNED NOT NULL,
    recipient INT UNSIGNED NOT NULL,
    status ENUM('pending', 'accepted', 'blocked') NOT NULL DEFAULT 'pending',
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deletedAt DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_friendships_requester_recipient (requester, recipient),
    KEY idx_friendships_recipient_status (recipient, status),
    CONSTRAINT fk_friendships_requester FOREIGN KEY (requester) REFERENCES users (id),
    CONSTRAINT fk_friendships_recipient FOREIGN KEY (recipient) REFERENCES users (id)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
];

const resetStatements = [
  'SET FOREIGN_KEY_CHECKS = 0;',
  'DROP TABLE IF EXISTS friendships;',
  'DROP TABLE IF EXISTS messages;',
  'DROP TABLE IF EXISTS direct_messages;',
  'DROP TABLE IF EXISTS communities;',
  'DROP TABLE IF EXISTS channel_groups;',
  'DROP TABLE IF EXISTS channels;',
  'DROP TABLE IF EXISTS roles;',
  'DROP TABLE IF EXISTS animes;',
  'DROP TABLE IF EXISTS users;',
  'SET FOREIGN_KEY_CHECKS = 1;',
];

module.exports = {
  schemaStatements,
  resetStatements,
};